# Deploy Python FastAPI (backend/) to Azure Web App
name: Build and deploy Python app to Azure Web App - app-002-gen10-step3-2-py-oshima9

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ★ CI上では依存インストールしない（Oryxがサーバ側でやる）
      #   代わりに backend/requirements.txt の存在だけ保証する
      - name: Ensure backend/requirements.txt exists (copy if root-only)
        run: |
          if [ ! -f backend/requirements.txt ] && [ -f requirements.txt ]; then
            echo "Copying ./requirements.txt -> backend/requirements.txt"
            cp requirements.txt backend/requirements.txt
          fi
          echo "Show backend tree:"
          ls -la backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree before deploy (debug)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "---- backend ----"
          ls -la backend || true
          test -f backend/requirements.txt || (echo "ERROR: backend/requirements.txt missing" && exit 1)

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "app-002-gen10-step3-2-py-oshima9"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32DCBC11FA764CD5A832E64BEA3D77BF }}
          package: ./backend
       




