# Docs: https://github.com/Azure/webapps-deploy
name: Build and deploy Python app to Azure Web App - app-002-gen10-step3-2-py-oshima9

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (auto-detect requirements.txt)
        run: |
          set -e
          python -m pip install --upgrade pip
          echo "PWD=$(pwd)"
          echo "Top-level files:" && ls -la || true
          echo "backend files:" && ls -la backend || true
          if [ -f requirements.txt ]; then
            echo "-> using ./requirements.txt"
            pip install -r requirements.txt
          elif [ -f backend/requirements.txt ]; then
            echo "-> using backend/requirements.txt"
            pip install -r backend/requirements.txt
          else
            echo "requirements.txt not found at ./ or ./backend"
            exit 1
          fi
      # ※ ここでpytest等を走らせたい場合はこの下に追記

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show tree before deploy (debug)
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "---- backend ----"
          ls -la backend || true

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "app-002-gen10-step3-2-py-oshima9"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_32DCBC11FA764CD5A832E64BEA3D77BF }}
          package: ./backend   # ← backend ディレクトリをそのまま送る

